### PR TITLE
Update URLs, to reflect changes in folder names

### PR DESCRIPTION
**Pull request by sahilseth**

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
?

**Comment by sahilseth** [comment]
This fixes the github installation, if one wants to use it instead of bioconductor.

**Comment by MarcinKosinski** [comment]
Which URLs :)?

2015-11-03 15:00 GMT+01:00 sseth <notifications@github.com>:

**Comment by sahilseth** [comment]
You may just ignore this. If you look at the 'Files Changed' tab of this pull request you would see, I make this minor change in the README document:

```
# delete
-install_github("mi2-warsaw/RTCGA.data/PANCAN12")
-install_github("mi2-warsaw/RTCGA.data/cnv")
# add
+install_github("mi2-warsaw/RTCGA.data/RTCGA.PANCAN12")
+install_github("mi2-warsaw/RTCGA.data/RTCGA.cnv")
```

It seems some time back, you had a folder cnv, which was may be renamed to RTCGA.cnv.

**Comment by MarcinKosinski** [comment]
I've reopened this and merged this PR :) thanks!
But this weekend we gonna have huge clean-up here

**Pull request merged**
